# Generated by Django 5.2.1 on 2025-06-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='object_id',
        ),
    ]
